Feature: createHotelBookings
Generated by Yest

Background: Init createHotelBookings


Scenario Outline:Generated test scenario

When I login with valid credentials
 And I select the value "<locations>" in the "location" dropdown

Examples: 
	| locations	|
	| Sydney   	|
	| Brisbane 	|


